title: Calyx
email: me@maetl.net
description: >
  A Ruby library for generating text with template expansion grammars.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: maetl
github_username:  maetl

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
